# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np
np.random.seed(123)

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.18.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.full(10, np.NaN)
print(null_vector)
print(null_vector.shape)

[nan nan nan nan nan nan nan nan nan nan]
(10,)


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("{} bytes".format(null_vector.itemsize * null_vector.size))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# ! np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.arange(10, 50)[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
# np.nonzero returns the indicies where non-zero values are located.
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
# np.eye returns a matrix with a diagonal of ones. The diagonal is placed in the 
# left upper left corner to the bottom right corner of an array.

np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
# np.random.randn function creates an array with d0, d1,..., dn
# The randn method creates a 3, 3x3 multidimensional arrays. 

np.random.randn(3, 3, 3)

array([[[-1.0856306 ,  0.99734545,  0.2829785 ],
        [-1.50629471, -0.57860025,  1.65143654],
        [-2.42667924, -0.42891263,  1.26593626]],

       [[-0.8667404 , -0.67888615, -0.09470897],
        [ 1.49138963, -0.638902  , -0.44398196],
        [-0.43435128,  2.20593008,  2.18678609]],

       [[ 1.0040539 ,  0.3861864 ,  0.73736858],
        [ 1.49073203, -0.93583387,  1.17582904],
        [-1.25388067, -0.6377515 ,  0.9071052 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.randn(10, 10)
print(a)
print(a.min())
print(a.max())

[[-1.4286807  -0.14006872 -0.8617549  -0.25561937 -2.79858911 -1.7715331
  -0.69987723  0.92746243 -0.17363568  0.00284592]
 [ 0.68822271 -0.87953634  0.28362732 -0.80536652 -1.72766949 -0.39089979
   0.57380586  0.33858905 -0.01183049  2.39236527]
 [ 0.41291216  0.97873601  2.23814334 -1.29408532 -1.03878821  1.74371223
  -0.79806274  0.02968323  1.06931597  0.89070639]
 [ 1.75488618  1.49564414  1.06939267 -0.77270871  0.79486267  0.31427199
  -1.32626546  1.41729905  0.80723653  0.04549008]
 [-0.23309206 -1.19830114  0.19952407  0.46843912 -0.83115498  1.16220405
  -1.09720305 -2.12310035  1.03972709 -0.40336604]
 [-0.12602959 -0.83751672 -1.60596276  1.25523737 -0.68886898  1.66095249
   0.80730819 -0.31475815 -1.0859024  -0.73246199]
 [-1.21252313  2.08711336  0.16444123  1.15020554 -1.26735205  0.18103513
   1.17786194 -0.33501076  1.03111446 -1.08456791]
 [-1.36347154  0.37940061 -0.37917643  0.64205469 -1.97788793  0.71226464
   2.59830393 -0.02462598  0.03414213  0.17954948]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.randn(30).mean()

0.0497014934515546

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a = np.ones((3, 3))
a[1][1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
padded_array = np.pad(a, 1)
padded_array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
# First time performing computation and comparison on np.nan
# It has no value yet, nothing is greater than np.nan... not even
# Infinity! Non-existence/absence of value is greater than
# That which has value... It's not even equal to itself?! 
# np.nan only recognizes itself inside a set. Noted.
print(0 * np.nan)
print(np.nan == np.nan)
print(1 > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(0-0)

nan
False
False
nan
True
False
0


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diagflat([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a = np.zeros(64).reshape(8, 8)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
# np.put?

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
a = np.random.randn(6, 7, 8)

In [22]:
# a.take(99)
a.item(99)

0.5907042178943853

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a = np.tile([[0, 1], [1, 0]], (4, 4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
rand_arr_5x5 = np.random.randn(5, 5)
num_min, num_max = rand_arr_5x5.min(), rand_arr_5x5.max()
num_mean, num_std = rand_arr_5x5.mean(), rand_arr_5x5.std()

In [25]:
normed_array = (rand_arr_5x5 - num_mean)/num_std
normed_array

array([[-0.43860693, -1.41118649,  0.57240611,  0.5051088 , -0.15674959],
       [ 0.25821525, -0.29788268,  0.79815603, -0.03837468, -0.44914981],
       [ 1.01581171,  1.42186773,  1.51580992, -1.33770207, -0.77891303],
       [-2.20957299, -0.41619746,  0.38637141, -0.28654385,  2.24324251],
       [-0.62126037, -1.45812484,  0.57317123,  0.06005487,  0.55004919]])

### Normalization

In [26]:
norm_arr_5x5 = (rand_arr_5x5 - num_min) / (num_max - num_min)
norm_arr_5x5

array([[0.39771827, 0.17929926, 0.62476855, 0.60965513, 0.46101695],
       [0.55420851, 0.4293217 , 0.6754668 , 0.48760123, 0.39535058],
       [0.72434726, 0.81553811, 0.83663536, 0.19580217, 0.32129334],
       [0.        , 0.40275092, 0.58298944, 0.43186814, 1.        ],
       [0.3566985 , 0.16875798, 0.62494038, 0.50970624, 0.6197477 ]])

### Standardization

In [27]:
rand_arr_5x5/ np.linalg.norm(rand_arr_5x5)

array([[-0.06249555, -0.25553904,  0.13817645,  0.12481887, -0.0065508 ],
       [ 0.07581394, -0.03456375,  0.18298466,  0.01694497, -0.06458817],
       [ 0.22618628,  0.30678274,  0.32542896, -0.24095341, -0.13004157],
       [-0.41400764, -0.05804758,  0.10125115, -0.03231315,  0.46981419],
       [-0.09874972, -0.26485565,  0.13832831,  0.03648186,  0.13373891]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [28]:
custom = np.dtype([("R", np.ubyte),
                   ("G", np.ubyte),
                   ("B", np.ubyte),
                   ("A", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
arr_1 = np.arange(15).reshape(5, 3)
arr_2 = np.arange(6).reshape(3, 2)
np.dot(arr_1, arr_2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
array = np.arange(10)

between_3_and_8 = (array >= 3) & (array <= 8)
array[between_3_and_8] *= -1

print(array)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5), -1))

9


Importing modules directly from numpy causes a Namespace collision between Python's built-in `range` function and numpy's `range` function.

In [32]:
from numpy import *
print(sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
vector = np.arange(0, 10)

In [34]:
vector * vector

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [35]:
2 << vector >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [36]:
vector <- vector

array([False, False, False, False, False, False, False, False, False,
       False])

In [37]:
1j*vector

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [38]:
vector/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
vector << vector >> vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
np.array(0) / np.array(0)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [41]:
np.array(0) // np.array(0)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [42]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [43]:
Z = np.random.randn(5, 5)

In [44]:
print(Z)

[[ 3.03787931e-01  2.43765761e-01 -2.12229888e+00 -7.26114028e-01
  -5.90324918e-01]
 [-3.47964338e-01 -4.48391638e-01  4.12818762e-01  6.00882509e-01
  -1.13164093e+00]
 [ 6.86804407e-01  5.85768139e-01  4.65770066e-01 -1.41789449e+00
   4.40582300e-01]
 [ 8.25954195e-02  9.60880075e-01  1.78435680e+00  1.58806789e+00
   1.12644172e-01]
 [-1.87469173e-03  6.31948284e-01 -1.11503995e+00 -1.45068314e+00
  -4.72530592e-01]]


In [45]:
np.where(Z > 0, np.ceil(Z), np.floor(Z))

array([[ 1.,  1., -3., -1., -1.],
       [-1., -1.,  1.,  1., -2.],
       [ 1.,  1.,  1., -2.,  1.],
       [ 1.,  1.,  2.,  2.,  1.],
       [-1.,  1., -2., -2., -1.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [46]:
arr_1 = np.arange(9).reshape(3, 3)
arr_2 = np.arange(0, 18, 2).reshape(3, 3)
print(arr_1,'\n\n' ,arr_2)
np.intersect1d(arr_1, arr_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


array([0, 2, 4, 6, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
# np.seterr(all='ignore')

In [48]:
np.array(0) / np.array(0)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [49]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [50]:
# np.datetime64?

In [51]:
# np.timedelta64?

https://numpy.org/doc/stable/reference/arrays.datetime.html

In [52]:
# np.datetime64('now')

In [53]:
np.datetime64('today') - np.timedelta64(1, 'D')

numpy.datetime64('2020-08-29')

In [54]:
np.datetime64('today')

numpy.datetime64('2020-08-30')

In [55]:
np.datetime64('today') + np.timedelta64(1, 'D')

numpy.datetime64('2020-08-31')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [56]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [57]:
# np.divide?
# This equation will only work on arrays of type float.
A = np.array([1, 2, 3, 4], dtype='float64')
B = np.array([1, 2, 3, 4], dtype='float64')

# We can use numpy.add to add A and B. We can assign the result to B.
np.add(A,B,out=B)

# Next we can np.divide to divide A by two. We can assign the result to A.
np.divide(A,2,out=A)

# Using np.negative, we can make the result from above negative. Assign the result to A.
np.negative(A,out=A)

# Once all operations are completed inside the parentheses, we can multiply A and B.
np.multiply(A,B,out=A)

array([ -1.,  -4.,  -9., -16.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [58]:
R = np.random.uniform(0, 7, 7)

In [59]:
R

array([5.39118422, 3.08323401, 5.90854224, 0.53342845, 3.36789829,
       3.26794797, 1.85029586])

In [60]:
# Using .astype we can cast values from float->int removing the
# decimal places.
R.astype('int')

array([5, 3, 5, 0, 3, 3, 1])

In [61]:
# This is cool! We can use the modulus to return the decimal values 
# From array R. We can subtract the decimal values from R.
R - R%1

array([5., 3., 5., 0., 3., 3., 1.])

In [62]:
# Using floor division we can remove the decimal places.
R // 1

array([5., 3., 5., 0., 3., 3., 1.])

In [63]:
# Using np.trunc we can remove decimal places.
# np.trunc?
np.trunc(R)

array([5., 3., 5., 0., 3., 3., 1.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
np.repeat([0, 1, 2, 3, 4], 5).reshape(5, 5)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [65]:
# Used hint
generator = range(11)

# np.fromiter takes a iterator function and returns an array
# with values of dtype float. count kwarg is set to -1
# to return all values from the iterable.
array = np.fromiter(generator, float, count=-1)
print(type(array))
print(array)

<class 'numpy.ndarray'>
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [66]:
# Used hint with answer
# np.linspace is a numpy generator that creates evenly spaced
# Numbers over a specified interval, here 0 to 1.
# I set kwarg endpoint=False to exclude 1 from the returned array.
# I can use slice indexing to remove the first value, 0, from the
# Returned array. By setting `num` positional arg. to 11 I generate
# 11 values, 1 of which is 0. The array returned has 10 evenly spaced
# numbers between 0 and 1 excluding both start and stop.

np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [67]:
r = np.random.randn(10)
np.sort(r)

array([-2.11090421, -0.89976143, -0.8588599 , -0.66932203, -0.20610043,
       -0.13464477, -0.1259801 ,  0.52650765,  1.22056891,  1.53966482])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [68]:
# Hint with solution used.
# np.sum?
# np.add.reduce?

In [69]:
small = np.arange(1,101).reshape(10, 10)

In [70]:
%%time
small.sum()

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 36 µs


5050

In [71]:
%%time
sum(small)

CPU times: user 41 µs, sys: 0 ns, total: 41 µs
Wall time: 43.6 µs


5050

In [72]:
%%time
# To get the correct sum from np.reduce.add, I need to set axis=None
# Otherwise I get the sum across rows
np.add.reduce(small, axis=None)

CPU times: user 24 µs, sys: 0 ns, total: 24 µs
Wall time: 26.9 µs


5050

In [73]:
np.add.reduce(small)

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [74]:
# Hint used
A = np.random.randn(3, 3)
B = np.random.randn(3, 3)

In [75]:
# np.array_equal only returns True if both arrays have the same
# Dimensions and elements.

np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [76]:
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.setflags.html
immutable_force = np.arange(9).reshape(3, 3)

immutable_force.setflags(write=False)
# immutable_force.flags.writeable = False
immutable_force[0] = 42

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [77]:
# https://en.wikipedia.org/wiki/Polar_coordinate_system
# Hint and solution used.
cartesian = np.random.random((10, 2))
cart_x, cart_y = cartesian[:,0], cartesian[:,1]

np.arctan2(cart_y, cart_x)

array([1.41591665, 0.39317285, 0.27939853, 1.43683581, 0.33878981,
       1.0298481 , 0.70032134, 0.87657927, 0.97274091, 0.68093297])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

``` python
np.argmax()
```
> Returns the indices of the maximum values along an axis.

In [78]:
a = np.random.random(10)
print(a.max())
a[a.argmax()] = 0
print(a.max())

0.9470674904902782
0.9153545066254917


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [79]:
# Hint and solution used.
# np.meshgrid?
# https://numpy.org/doc/stable/user/basics.rec.html
# Interesting. Constructing an array with explicit dtypes
# causes the elements to be grouped together in tuples.
# In each element the first position is -> float, second position is
# int.
np.zeros((5, 5), dtype=[('a', float),('b', int)])

array([[(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)]],
      dtype=[('a', '<f8'), ('b', '<i8')])

In [80]:
coordinates = np.zeros((5,5), dtype=[('x',float),('y',float)])

# np.meshgrid only accepts 1-D arrays! as arguments
# I have to assign the values from meshgrid separately. 
coordinates['x'], coordinates['y'] = np.meshgrid(
    np.linspace(0,1,5),
    np.linspace(0,1,5))

print(coordinates)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [81]:
# https://en.wikipedia.org/wiki/Cauchy_matrix
# http://math.sjtu.edu.cn/Conference/SCAC/slide/AlisonGordon.pdf
# Change the shape of X or Y allows me to perform the Cauchy Martix
# Calculation.
X = np.array([10, 20, 70]).reshape(-1, 1)
Y = np.array([40, 60, 30, 100]) #.reshape(-1, 1)

1/(X-Y)

array([[-0.03333333, -0.02      , -0.05      , -0.01111111],
       [-0.05      , -0.025     , -0.1       , -0.0125    ],
       [ 0.03333333,  0.1       ,  0.025     , -0.03333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [82]:
# print(np.iinfo('int'))
print(np.iinfo('int32'))
# NINE QUINTERINTINOTILLION!!!!!!
print(np.iinfo('int64'))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆)

In [83]:
# np.set_printoptions?

# Reading the docs, I can pass sys.maxsize to print all elements of
# An array rather than the summarized repr.
printable = np.arange(1, 1_000)
np.set_printoptions('sys.maxsize')
printable

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [86]:
%%timeit # (: 
# Used hint and solution
# Creating a vector using the range function.
vector = np.arange(100_000_000)

# Selecting a scalar from the random uniform distribution of 100,000,000
scalar = np.random.uniform(0,100_000_000)

# I can perform vectorization to subtract the scalar from every
# Value in vector. I take the absolute value of the operation
# To find the closet value to a scalar irregardless of positive/negative
# I can use argmin() to return the index that holds the closest value
# To the given scalar
index = (np.abs(vector-scalar)).argmin()

# Return the number
print(scalar)
print(vector[index])

62496445.32088534
62496445
55441213.15655141
55441213
97567126.63530815
97567127
75547439.141811
75547439
54481324.940761656
54481325
17403209.053872038
17403209
90411421.68501332
90411422
20583778.26833102
20583778
1.2 s ± 25.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)