# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [40]:
import numpy as np
np.random.seed(123)

#### 2. Print the numpy version and the configuration (★☆☆)

In [41]:
np.__version__

'1.18.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [42]:
null_vector = np.full(10, np.NaN)
print(null_vector)
print(null_vector.shape)

[nan nan nan nan nan nan nan nan nan nan]
(10,)


#### 4. How to find the memory size of any array (★☆☆)

In [43]:
print("{} bytes".format(null_vector.itemsize * null_vector.size))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [44]:
! np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [50]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [51]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [52]:
np.arange(10, 50)[:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [53]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [54]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [55]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [56]:
np.random.randn(3, 3, 3)

array([[[-1.0856306 ,  0.99734545,  0.2829785 ],
        [-1.50629471, -0.57860025,  1.65143654],
        [-2.42667924, -0.42891263,  1.26593626]],

       [[-0.8667404 , -0.67888615, -0.09470897],
        [ 1.49138963, -0.638902  , -0.44398196],
        [-0.43435128,  2.20593008,  2.18678609]],

       [[ 1.0040539 ,  0.3861864 ,  0.73736858],
        [ 1.49073203, -0.93583387,  1.17582904],
        [-1.25388067, -0.6377515 ,  0.9071052 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
a = np.random.randn(10, 10)
print(a.min())
print(a.max())

-2.7985891054607244
2.5983039272693147


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
np.random.randn(30).mean()

0.0497014934515546

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [59]:
a = np.ones((3, 3))
a[1][1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [60]:
padded_array = np.pad(a, 1)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [61]:
# First time performing computation and comparison on np.nan
# It has no value yet, nothing is greater than np.nan... not even
# Infinity! Non-existence/absence of value is greater than
# That which has value... It's not even equal to itself?! 
# np.nan only recognizes itself inside a set. Noted.
print(0 * np.nan)
print(np.nan == np.nan)
print(1 > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(0-0)

nan
False
False
nan
True
False
0


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [62]:
np.diagflat([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [69]:
a = np.zeros(64).reshape(8, 8)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [70]:
# np.put?

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
a = np.random.randn(6, 7, 8)

In [72]:
# a.take(99)
a.item(99)

0.823896442609245

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [73]:
a = np.tile([[0, 1], [1, 0]], (4, 4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [89]:
rand_arr_5x5 = np.random.randn(5, 5)
num_min, num_max = rand_arr_5x5.min(), rand_arr_5x5.max()

### Normalization

In [92]:
norm_arr_5x5 = (rand_arr_5x5 - num_min) / (num_max - num_min)
norm_arr_5x5

array([[0.64001795, 0.38321263, 0.76441707, 0.58345519, 0.44504134],
       [0.47021248, 1.        , 0.58446488, 0.52497234, 0.47517719],
       [0.68095897, 0.23139455, 0.46662544, 0.        , 0.40466257],
       [0.6476685 , 0.74166387, 0.60510322, 0.61108425, 0.1966369 ],
       [0.37915995, 0.75787926, 0.4063422 , 0.47457807, 0.35678487]])

### Standardization

In [93]:
array/ np.linalg.norm(array)

array([[ 0.05865374, -0.39629441, -0.32683124, -0.127959  ,  0.17626442],
       [ 0.13005834,  0.10059707,  0.12155222, -0.18762006,  0.11638279],
       [-0.17839129,  0.18342876, -0.09886246,  0.05453221, -0.36296549],
       [-0.26118994,  0.21119158,  0.13394472, -0.23583323,  0.24893349],
       [-0.21121229,  0.00386514, -0.09296351, -0.17880402,  0.2261523 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [94]:
custom = np.dtype([("R", np.ubyte),
                   ("G", np.ubyte),
                   ("B", np.ubyte),
                   ("A", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [95]:
arr_1 = np.arange(15).reshape(5, 3)
arr_2 = np.arange(6).reshape(3, 2)
np.dot(arr_1, arr_2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [97]:
array = np.arange(10)

between_3_and_8 = (array >= 3) & (array <= 8)
array[between_3_and_8] *= -1

print(array)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5), -1))

9


Importing modules directly from numpy causes a Namespace collision between Python's built-in `range` function and numpy's `range` function.

In [48]:
from numpy import *
print(sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [126]:
vector = np.arange(0, 10)

In [127]:
vector * vector

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [128]:
2 << vector >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [129]:
vector <- vector

array([False, False, False, False, False, False, False, False, False,
       False])

In [130]:
1j*vector

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [131]:
vector/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
vector << vector >> vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [133]:
np.array(0) / np.array(0)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [134]:
np.array(0) // np.array(0)

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [135]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [173]:
Z = np.random.randn(5, 5)

In [174]:
print(Z)

[[-0.23934741  1.21551708  1.30709842 -0.15686211 -0.17657868]
 [-0.29602896 -0.13523278 -0.56964647 -1.43921074 -1.37929162]
 [-0.71238124 -1.00462189  0.93440535 -1.09401933  0.04259251]
 [ 0.45987153  0.85401087  2.25902185  0.76746432  0.55385939]
 [-0.44370818  0.59714702  0.15341911  0.32245534 -0.15689228]]


In [178]:
np.where(Z > 0, np.ceil(Z), np.floor(Z))

array([[-1.,  2.,  2., -1., -1.],
       [-1., -1., -1., -2., -2.],
       [-1., -2.,  1., -2.,  1.],
       [ 1.,  1.,  3.,  1.,  1.],
       [-1.,  1.,  1.,  1., -1.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [185]:
arr_1 = np.arange(9).reshape(3, 3)
arr_2 = np.arange(0, 18, 2).reshape(3, 3)
np.intersect1d(arr_1, arr_2)

array([0, 2, 4, 6, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [196]:
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [193]:
np.array(0) / np.array(0)

nan

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [194]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [203]:
np.datetime64?

In [204]:
np.timedelta64?

https://numpy.org/doc/stable/reference/arrays.datetime.html

In [ ]:
# np.datetime64('now')

In [212]:
np.datetime64('today') - np.timedelta64(1, 'D')

numpy.datetime64('2020-08-17')

In [215]:
np.datetime64('today')

numpy.datetime64('2020-08-16')

In [214]:
np.datetime64('today') + np.timedelta64(1, 'D')

numpy.datetime64('2020-08-15')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [220]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)